version: "3"

tasks:
  generateSSO:
    desc: "Generate sso code from proto files"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generateCRUD:
    desc: "Generate crud code from proto files"
    cmds:
      - protoc -I proto proto/crud/crud.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative